<?php
/**
 * Test case
 *
 * Copyright (c) 2007-2009, Mayflower GmbH
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *
 *   * Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in
 *     the documentation and/or other materials provided with the
 *     distribution.
 *
 *   * Neither the name of Mayflower GmbH nor the names of his
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * @category   PHP_CodeBrowser
 * @package    PHP_CodeBrowser
 * @subpackage PHPUnit
 * @author     Elger Thiele <elger.thiele@mayflower.de>
 * @copyright  2007-2009 Mayflower GmbH
 * @license    http://www.opensource.org/licenses/bsd-license.php  BSD License
 * @version    SVN: $Id$
 * @link       http://www.phpunit.de/
 * @since      File available since 1.0
 */

require_once realpath(dirname( __FILE__ ) . '/../AbstractTests.php');

/**
 * cbErrorHandlerTests
 *
 * @category   PHP_CodeBrowser
 * @package    PHP_CodeBrowser
 * @subpackage PHPUnit
 * @author     Elger Thiele <elger.thiele@mayflower.de>
 * @copyright  2007-2009 Mayflower GmbH
 * @license    http://www.opensource.org/licenses/bsd-license.php  BSD License
 * @version    Release: @package_version@
 * @link       http://www.phpunit.de/
 * @since      Class available since 1.0
 */
class cbErrorHandlerTest extends cbAbstractTests 
{
    /**
     * ErrorHandler object to test
     * 
     * @var cbErrorHandler
     */
    protected $_cbErrorHandler;
    
    /**
     * Mock object for cbXMLHandler
     * 
     * @var object
     */
    protected $_mockXMLHandler;
    
    /**
     * Reference file to check.
     * All PHP_CodeBrowser errors and XML files relay on this file.
     * 
     * @var string
     */
    protected $_fileName = 'JSGenerator.php';
    
    /**
     * Needed attributes for phpcb errors
     * 
     * @var array
     */
    protected $_neededKeys = array('line', 'to-line', 'source', 'severity', 'description');
    
    /**
     * (non-PHPdoc)
     * @see tests/cbAbstractTests#setUp()
     */
    protected function setUp()
    {
        parent::setUp();
        $this->_mockXMLHandler = $this->_getMockXMLHandler();
        $this->_cbErrorHandler = new cbErrorHandler($this->_mockXMLHandler);
    }
    
    /**
     * (non-PHPdoc)
     * @see tests/cbAbstractTests#tearDown()
     */
    protected function tearDown()
    {
        parent::tearDown();
    }
    
    /**
     * Test constructor if objects are initialized properly
     * 
     * @return void
     */
    public function test__construct()
    {
        $this->assertTrue($this->_cbErrorHandler->cbXMLHandler instanceof cbXMLHandler);
    }
    
    /**
     * Test if PHP_CodeBrowser errors are loaded properly from XML file and 
     * provide all needed attributes.
     * 
     * SimpleXMLObject is generated by MockObject.
     * 
     * @return void
     */
    public function testGetErrorsByFile()
    {   
        $this->_mockXMLHandler
            ->expects($this->once())
            ->method('loadXML')
            ->with($this->equalTo(self::$_cbXMLFile))
            ->will($this->returnValue(simplexml_load_file(self::$_cbXMLFile)));
            
        $list = $this->_cbErrorHandler->getErrorsByFile(self::$_cbXMLFile, $this->_fileName);
        
        $this->assertType('SimpleXMLElement', $list);
        
        foreach ($list as $item) foreach($item->attributes() as $key => $value) {
            $this->assertTrue(in_array($key, $this->_neededKeys));
            $this->assertNotNull($value);
        }
    }
    
    /**
     * Test if proper file is extrected from XML file.
     * 
     * SimpleXMLObject is generated by MockObject.
     * 
     * @return void
     */
    public function testGetFilesWithErrors()
    {
        $this->_mockXMLHandler
            ->expects($this->once())
            ->method('loadXML')
            ->with($this->equalTo(self::$_cbXMLFile))
            ->will($this->returnValue(simplexml_load_file(self::$_cbXMLFile)));
            
        $this->_mockXMLHandler
            ->expects($this->atLeastOnce())
            ->method('countItems')
            ->will($this->returnValue(rand(1,100)));
        
        $files = $this->_cbErrorHandler->getFilesWithErrors(self::$_cbXMLFile);
        
        $this->assertTrue(5 === count($files[0]));
        $this->assertEquals($this->_fileName, $files[0]['complete']);
    }
}