<?php // this is an autogenerated file - do not edit (created Mon, 05 Sep 2011 09:22:14 +0200)
function autoload4e6478a62c1e5($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'cbclicontroller' => '/CLIController.php',
            'cberrorcheckstyle' => '/Plugins/ErrorCheckstyle.php',
            'cberrorcoverage' => '/Plugins/ErrorCoverage.php',
            'cberrorcpd' => '/Plugins/ErrorCPD.php',
            'cberrorcrap' => '/Plugins/ErrorCRAP.php',
            'cberrorpadawan' => '/Plugins/ErrorPadawan.php',
            'cberrorpmd' => '/Plugins/ErrorPMD.php',
            'cbfile' => '/File.php',
            'cbiohelper' => '/Helper/IOHelper.php',
            'cbissue' => '/Issue.php',
            'cbissuexml' => '/IssueXml.php',
            'cbpluginsabstract' => '/PluginsAbstract.php',
            'cbsourcehandler' => '/SourceHandler.php',
            'cbviewabstract' => '/View/ViewAbstract.php',
            'cbviewreview' => '/View/ViewReview.php'
         );
      }
   $cn = strtolower($class);
   if (isset($classes[$cn])) {
      require dirname(__FILE__) . $classes[$cn];
   }
}
spl_autoload_register('autoload4e6478a62c1e5');
